"""empty message

Revision ID: 083872aa6d8c
Revises: cbd544639086
Create Date: 2018-03-01 23:07:06.098338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083872aa6d8c'
down_revision = 'cbd544639086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=128), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=516), nullable=True),
    sa.Column('blogpost_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blogpost_id'], ['blog_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
